services:
    mysql:
        image: 'mysql/mysql-server:8.0'
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
        profiles:
            - dev
            - db
    redis:
        image: 'redis:alpine'
        restart: unless-stopped
        expose:
            - '6379'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
        profiles:
            - dev
            - cache
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        restart: unless-stopped
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'meilisearch:/meili_data'
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s
        profiles:
            - dev
            - search
    mailpit:
        image: 'axllent/mailpit:latest'
        restart: unless-stopped
        ports:
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        profiles:
            - dev
    web:
        image: rpungello/laravel-nginx:franken-reverb
        ports:
            - "${WEB_PORT:-80}:80"
        restart: unless-stopped
        depends_on:
            - app
        profiles:
            - app
            - prod
    app:
        image: rpungello/webhook-tester:stable
        restart: unless-stopped
        expose:
            - 80
        env_file: stack.env
        profiles:
            - app
            - prod
    worker:
        image: rpungello/webhook-tester:stable
        restart: unless-stopped
        env_file: stack.env
        entrypoint:
            - 'php'
            - 'artisan'
            - 'horizon'
        profiles:
            - work
            - prod
    scheduler:
        image: rpungello/webhook-tester:stable
        env_file: stack.env
        restart: unless-stopped
        entrypoint:
            - 'php'
            - 'artisan'
            - 'schedule:work'
        profiles:
            - work
            - prod
    reverb:
        image: rpungello/webhook-tester:stable
        expose:
            - 8080
        profiles:
            - dev
            - prod
        env_file: stack.env
        entrypoint:
            - 'php'
            - 'artisan'
            - 'reverb:start'
        restart: unless-stopped
volumes:
    mysql:
        driver: local
    redis:
        driver: local
    meilisearch:
        driver: local
