services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-}'
        image: rpungello/webhook-tester:sail
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        profiles:
            - dev
        depends_on:
            - mysql
            - redis
            - meilisearch
            - mailpit
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
        profiles:
            - dev
            - db
    redis:
        image: 'redis:alpine'
        expose:
            - '6379'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
        profiles:
            - dev
            - cache
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'meilisearch:/meili_data'
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s
        profiles:
            - dev
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        profiles:
            - dev
    web:
        image: rpungello/laravel-nginx:franken-reverb
        ports:
            - "${WEB_PORT:-80}:80"
        restart: unless-stopped
        depends_on:
            - app
        profiles:
            - app
            - prod
    app:
        image: rpungello/webhook-tester:stable
        restart: unless-stopped
        expose:
            - 80
        env_file: .env
        profiles:
            - app
            - prod
    worker:
        image: rpungello/webhook-tester:stable
        restart: unless-stopped
        env_file: .env
        entrypoint:
            - 'php'
            - 'artisan'
            - 'horizon'
        profiles:
            - work
            - prod
    scheduler:
        image: rpungello/webhook-tester:stable
        env_file: .env
        restart: unless-stopped
        entrypoint:
            - 'cron'
            - '-f'
        profiles:
            - work
            - prod
    reverb:
        image: rpungello/webhook-tester:stable
        ports:
            - '${FORWARD_REVERB_PORT:-8080}:8080'
        profiles:
            - dev
            - prod
        env_file: .env
        entrypoint:
            - 'php'
            - 'artisan'
            - 'reverb:start'
        restart: unless-stopped
volumes:
    mysql:
        driver: local
    redis:
        driver: local
    meilisearch:
        driver: local
